### ISSUE TITLE
DataFile.put Documentation and Usage

### ISSUE THREAD

**Issue by kalexmills** [algorithmiaio/algorithmia-java#11]
It would be nice if the documentation for DataFile mentioned that these methods are blocking.

 Also, I'm not sure what the intended usage of the put methods are. InputStreams are typically read from, whereas with the put method we are trying to write to the file. It seems much more "usual" to use an OutputStream, but you're clearly using an API that wants an InputStream.

Not sure how to write to a file using this API, and the documentation doesn't explain much.

https://github.com/algorithmiaio/algorithmia-java/blob/37fe06f0162b3ada9a1793c1781fafa8d7a52412/src/main/java/com/algorithmia/data/DataFile.java#L106

**Comment by peckjon** [comment]
@kalexmills the put method to which you're referring takes an inputstream b/c it will read input from that stream, and upload it to the remote file.

This documentation may be more helpful: http://docs.algorithmia.com/?java#upload-a-file

**Comment by kalexmills** [comment]
Thanks for the pointer to that documentation. I'm still learning the system here. I'm looking to see if there's more convenient API than what is currently being exposed. I hope this isn't too annoying.

It doesn't appear that there are any examples from the link you gave me which use an InputStream (below is what I am seeing).

```
DataDirectory robots = client.dir("data://.my/robots");

// Upload local file
robots.putFile(new File("/path/to/Optimus_Prime.png"));
// Write a text file
robots.file("Optimus_Prime.txt").put("Leader of the Autobots");
// Write a binary file
robots.file("Optimus_Prime.key").put(new byte[] { (byte)0xe0, 0x4f, (byte)0xd0, 0x20 });
```

To learn the system I'm trying to develop a simple Algorithmia algorithm which edits a file by reading in an input file and writing some modified content back out to an output file. Ideally, I'd like to set this up so that I can read the input file line-by-line and write the output file in the same manner. But it seems from the current API that the only way to do this is to write the entire file at once, unless the InputStream exposes some other functionality.

But even if that functionality does exists, I don't see how I could write my output to an InputStream. InputStreams are typically meant for reading only. Is there some way for me to write to one using the standard libraries without writing a custom class that extends InputStream?

**Comment by peckjon** [comment]
I'd live to help you out with this personally @kalexmills -- head over to http://algorithmia.com and click the chat button in the lower-right corner, and ask for Jon!
