### ISSUE TITLE
com.algorithmia.APIException: 308 unexpected API response

### ISSUE THREAD

**Issue by toderesa97** [algorithmiaio/algorithmia-java#17]
I'm getting this exception while executing the example code found on your [website](https://algorithmia.com/algorithms/nlp/Summarizer).

```
Exception in thread "main" com.algorithmia.APIException: 308 unexpected API response: 
	at com.algorithmia.algo.Algorithm.pipeRequest(Algorithm.java:145)
	at com.algorithmia.algo.Algorithm.pipe(Algorithm.java:96)
```

Have tried the same using cURL and everything works fine, even with python so my guessing it has something to do with HttpClient or Java itself.

 [Details]
 - IDE: IntelliJ ULTIMATE 2019.1
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Thanks for any help you can provide.
Tomás.

**Comment by victcebesp** [comment]
The same happening here!
I am using MacOS 10.14.2.
When calling the algorithm via cULR or using python it correctly works. Nevertheless, **to make it work from JAVA, I need to have a proxy such as Charles.**

Any clue about what is happening?
Thank you very much!

Víctor Ceballos Espinosa

**Comment by kennydaniel** [comment]
Thanks for reporting this, it is being fixed by PR #16 and I will have it published today as version 1.0.16 of the client.

**Comment by kennydaniel** [comment]
@toderesa97 @victcebesp algorithmia-client 1.0.16 is live on maven now. That should fix the 308 error. Please let me know if you still hit any problems!

**Comment by toderesa97** [comment]
Hello @kennydaniel,

 Indeed, the 308 is gone. Thanks.

Tomás.

**Comment by victcebesp** [comment]
Hey @kennydaniel! Everything is correctly working now! Awesome job, thank you very much for your fast replies.
