### ISSUE TITLE
Async http connections limited per client

### ISSUE THREAD

**Issue by pmcq** [algorithmiaio/algorithmia-java#7]
In order to truly make more than 2 simultaneous async calls, must create multiple Algorithmia clients due to a limitation in the default httpasyncclient.

https://github.com/algorithmiaio/algorithmia-java/commit/42497afb60d8ba7f182f3ee13b9b551dba541d6e

**Comment by Argoday** [comment]
also: see comment on https://github.com/algorithmiaio/algorithmia-java/commit/fcf6015f5f2e1dedc959eb259deff9618ceb5382

**Comment by Argoday** [comment]
and: looks like the ConnPoolControl methods enable easy override without creatting additional clients - just need to call the setters
